language: python

sudo: required
dist: trusty

python:
  - 2.7

services:
  - docker

install:
  - git clone https://github.com/avalon-studio/core.git
  - docker run --name avalon-mongo -d mongo
  - docker build -t pyblish/avalon -f Dockerfile-maya2016 .

script:
  - >
    PYTHONPATH=$(pwd)/core 
    docker run
    --rm
    -v $(pwd):/workspace
    --link avalon-mongo:mongo
    -e COVERALLS_REPO_TOKEN
    -e TRAVIS_JOB_ID
    -e AVALON_MONGO=mongodb://mongo:27017
    pyblish/avalon
